- name: approved
  color: 'a0bdd6'
- name: blocked
  color: '822d31'
  description: PR is blocked by something
- name: bug
  color: 'd73a4a'
- name: chore
  color: 'ffffff'
- name: dependencies
  color: '276bd1'
- name: documentation
  color: '0075ca'
- name: duplicate
  color: 'cfd3d7'
- name: feature
  color: 'ffff00'
- name: help wanted
  color: '008672'
- name: invalid
  color: 'e4e669'
- name: refactor
  color: '74e1c6'
- name: question
  color: 'd876e3'
- name: wontfix
  color: 'ffffff'
  description: This will not be worked on
