name: Sync Renovate Config

on:
  push:
    branches:
      - main
    paths:
      - '.github/renovate.json'
      - '.github/workflows/sync-renovate-config.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
    SyncRenovateConfig:
        name: Sync Renovate Config
        runs-on: ubuntu-latest
        steps:
          - name: Generate app token
            uses: actions/create-github-app-token@v3
            id: app-token
            with:
                client-id: ${{ vars.APP_ID }}
                private-key: ${{ secrets.APP_PRIVATE_KEY }}
                permission-contents: write
                permission-pull-requests: write

          - name: Checkout
            uses: actions/checkout@v7
            with:
              fetch-depth: 0
              token: ${{ steps.app-token.outputs.token }}
            
          - name: Copy renovate config to root
            run: |
              cp .github/renovate.json yuanstuffs-renovate.json
              
          - name: Get GitHub App User ID
            id: get-user-id
            run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
            env:
              GH_TOKEN: ${{ steps.app-token.outputs.token }}

          - name: Setup Git
            run: |
              # git config --local user.email "yuan-utilities[bot]@users.noreply.github.com"
              # git config --local user.name "yuan-utilities[bot]"
              git config --local user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
              git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
            env:
              GH_TOKEN: ${{ steps.app-token.outputs.token }}
          
          # - name: Commit files
          #   run: |
          #     git add yuanstuffs-renovate.json
          #     if ! git diff-index --quiet HEAD --; then
          #       git commit -nsm "chore(renovate): sync config" -m "Original Commit: ${GITHUB_SHA}"
          #       git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
          #     fi

          - name: Commit & Create Pull Request
            uses: peter-evans/create-pull-request@v6
            id: cpr
            with:
              token: ${{ steps.app-token.outputs.token }}
              commit-message: "chore(renovate): sync config"
              title: "chore(renovate): sync config"
              body: "Original Commit: ${GITHUB_SHA}"
              branch: "sync-renovate-config"
              delete-branch: true
              add-paths: |
                yuanstuffs-renovate.json
              labels: |
                approved:yuansheng1549
          - name: Enable Pull Request Automerge
            run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-url }}"
            env:
              GH_TOKEN: ${{ steps.app-token.outputs.token }}
